// employee
export const EMPLOYEELIST = "EMPLOYEELIST";
export const ADDEMPLOYEE = "ADDEMPLOYEE"


// parkinglot

export const PARKINGLOTLIST = "PARKINGLOTLIST"
export const ADDPARKINGLOT = "ADDPARKINGLOT"
export const MODIFYPARKINGLOT = "MODIFYPARKINGLOT"

// order
export const ORDERSLIST = "ORDERSLIST"


//parkinglot in dashboard
export const PARKINGLOTLISTINDASHBOARD="PARKINGLOTLISTINDASHBOARD"
